/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JDesktopPane;

/**
 *
 * @author Usuario
 */
public class FrmLicencias extends javax.swing.JFrame {

    private JDesktopPane desktopPane;

    /**
     * Creates new form FrmLicencias
     */
    public FrmLicencias() {
        initComponents();
        desktopPane = new JDesktopPane();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jDesktopPaneLicencias = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemIngresarCliente = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemAgregarOficiales = new javax.swing.JMenuItem();
        MenuInicioSesion = new javax.swing.JMenuItem();
        MenuCambioContrasena = new javax.swing.JMenuItem();
        JMENUPRUEBAS = new javax.swing.JMenu();
        MenuAgregarPruebas = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPaneLicenciasLayout = new javax.swing.GroupLayout(jDesktopPaneLicencias);
        jDesktopPaneLicencias.setLayout(jDesktopPaneLicenciasLayout);
        jDesktopPaneLicenciasLayout.setHorizontalGroup(
            jDesktopPaneLicenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2087, Short.MAX_VALUE)
        );
        jDesktopPaneLicenciasLayout.setVerticalGroup(
            jDesktopPaneLicenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        jMenu1.setText("Clientes");

        jMenuItemIngresarCliente.setText("AgregarClientes");
        jMenuItemIngresarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIngresarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemIngresarCliente);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Oficiales");

        jMenuItemAgregarOficiales.setText("AgregarOficiales");
        jMenuItemAgregarOficiales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarOficialesActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemAgregarOficiales);

        MenuInicioSesion.setText("Iniciar Sesión");
        MenuInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuInicioSesionActionPerformed(evt);
            }
        });
        jMenu4.add(MenuInicioSesion);

        MenuCambioContrasena.setText("Cambiar Contraseña");
        MenuCambioContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCambioContrasenaActionPerformed(evt);
            }
        });
        jMenu4.add(MenuCambioContrasena);

        jMenuBar1.add(jMenu4);

        JMENUPRUEBAS.setText("AgregarPruebas");

        MenuAgregarPruebas.setText("AgregarPruebas");
        MenuAgregarPruebas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAgregarPruebasActionPerformed(evt);
            }
        });
        JMENUPRUEBAS.add(MenuAgregarPruebas);

        jMenuBar1.add(JMENUPRUEBAS);

        jMenu5.setText("Citas");

        jMenuItem2.setText("AgregarCitas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneLicencias)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPaneLicencias)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemIngresarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIngresarClienteActionPerformed
        // TODO add your handling code here:
        InternalFrameClientes c = new InternalFrameClientes();
        jDesktopPaneLicencias.add(c);
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItemIngresarClienteActionPerformed

    private void jMenuItemAgregarOficialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarOficialesActionPerformed
        // TODO add your handling code here:
        InternalFrameOficiales o = new InternalFrameOficiales();
        jDesktopPaneLicencias.add(o);
        o.setVisible(true);
    }//GEN-LAST:event_jMenuItemAgregarOficialesActionPerformed

    private void MenuInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuInicioSesionActionPerformed
        // TODO add your handling code here:
        IniciarSesionOficial o = new IniciarSesionOficial();
        jDesktopPaneLicencias.add(o);
        o.setVisible(true);
    }//GEN-LAST:event_MenuInicioSesionActionPerformed

    private void MenuCambioContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCambioContrasenaActionPerformed
        // TODO add your handling code here:
        CambioContrasenaOficial o = new CambioContrasenaOficial();
        jDesktopPaneLicencias.add(o);
        o.setVisible(true);
    }//GEN-LAST:event_MenuCambioContrasenaActionPerformed

    private void MenuAgregarPruebasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAgregarPruebasActionPerformed
        InternalFrameFormPruebas o = new InternalFrameFormPruebas();
        jDesktopPaneLicencias.add(o);
        o.setVisible(true);
    }//GEN-LAST:event_MenuAgregarPruebasActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        InternalFrameCita a = new InternalFrameCita();
        jDesktopPaneLicencias.add(a);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLicencias.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLicencias.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLicencias.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLicencias.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLicencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMENUPRUEBAS;
    private javax.swing.JMenuItem MenuAgregarPruebas;
    private javax.swing.JMenuItem MenuCambioContrasena;
    private javax.swing.JMenuItem MenuInicioSesion;
    public static javax.swing.JDesktopPane jDesktopPaneLicencias;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemAgregarOficiales;
    private javax.swing.JMenuItem jMenuItemIngresarCliente;
    // End of variables declaration//GEN-END:variables
}
