/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Controller.Agenda.ControllerPruebas;
import Models.Agenda.Citas;
import Models.Agenda.DTO.PruebasDTO;
import Models.Agenda.Pruebas;
import Models.Personas.Clientes;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author UTN
 */
public class InternalFrameFormPruebas extends javax.swing.JInternalFrame {
    private ControllerPruebas control;
    /**
     * Creates new form InternalFrameFormPruebas
     */
    public InternalFrameFormPruebas() {
        initComponents();
        control = new ControllerPruebas(this);
        this.Desabilitar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPresente = new javax.swing.JRadioButton();
        txtAusente = new javax.swing.JRadioButton();
        lbliDOFICIAL = new javax.swing.JLabel();
        txtCedulaOficial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombreOficial = new javax.swing.JTextField();
        lblCedula = new javax.swing.JLabel();
        txtCedulaCliente = new javax.swing.JTextField();
        lblNombreCliente = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNota = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtObservaciones = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        txtHoraPrueba = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFechaPrueba = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIDPRUEBA = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Pruebas");

        jLabel2.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        jLabel2.setText("Estado");

        buttonGroup1.add(txtPresente);
        txtPresente.setText("Presente");
        txtPresente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPresenteActionPerformed(evt);
            }
        });

        buttonGroup1.add(txtAusente);
        txtAusente.setText("Ausente");
        txtAusente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAusenteActionPerformed(evt);
            }
        });

        lbliDOFICIAL.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        lbliDOFICIAL.setText("CedulaOficial");

        jLabel3.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        jLabel3.setText("NombreOficial");

        lblCedula.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        lblCedula.setText("CedulaCliente");

        lblNombreCliente.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        lblNombreCliente.setText("NombreCliente");

        jLabel4.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        jLabel4.setText("Nota");

        jLabel5.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        jLabel5.setText("Estado");

        jLabel6.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        jLabel6.setText("Observaciones");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cedula", "NombreCompleto", "Hora", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        txtHoraPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraPruebaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        jLabel7.setText("Fecha");

        jLabel8.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        jLabel8.setText("Hora");

        jLabel9.setFont(new java.awt.Font("sansserif", 2, 18)); // NOI18N
        jLabel9.setText("idCita");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCedula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(lblNombreCliente)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbliDOFICIAL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCedulaOficial, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(180, 180, 180)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreOficial, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel5))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(txtIDPRUEBA, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFechaPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addGap(42, 42, 42)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHoraPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel8)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAusente)
                                            .addComponent(txtPresente))))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnAgregar)
                .addGap(27, 27, 27)
                .addComponent(btnModificar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar)
                            .addComponent(btnEliminar)
                            .addComponent(btnModificar))
                        .addContainerGap(96, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(txtAusente)
                                        .addGap(39, 39, 39))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtHoraPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFechaPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtIDPRUEBA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(70, 70, 70)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbliDOFICIAL)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtCedulaOficial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                    .addComponent(txtNombreOficial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCedula)
                                    .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombreCliente)
                                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPresente)))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(314, 314, 314))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAusenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAusenteActionPerformed
        this.txtObservaciones.setEnabled(false);
        this.txtObservaciones.setText("EL CLIENTE NO SE PRESENTO");
        this.txtNota.setEnabled(false);
        this.txtNota.setText("0");
        this.txtEstado.setText("REPROBADO TONTIN");
    }//GEN-LAST:event_txtAusenteActionPerformed

    private void txtPresenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPresenteActionPerformed
       this.Habilitar();
        this.txtObservaciones.setEnabled(true);
       this.txtObservaciones.setText( "");
       this.txtNota.setEnabled(true);
       this.txtNota.setText("");
       this.txtEstado.setText("");
    }//GEN-LAST:event_txtPresenteActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        SimpleDateFormat inputFormat = new SimpleDateFormat("yyyy/MM/dd");
        try{
            Date fecha = inputFormat.parse(this.txtFechaPrueba.getText());
            Pruebas p = new Pruebas(Integer.parseInt(this.txtIDPRUEBA.getText()), this.txtCedulaOficial.getText(), this.txtCedulaCliente.getText(), this.txtObservaciones.getText(), Integer.parseInt(this.txtNota.getText()), this.txtEstado.getText(), fecha, this.txtHoraPrueba.getText());
            this.control.eliminar(p);
            this.limpiar();
        }catch(ParseException ex){
            JOptionPane.showMessageDialog(this, "Error no se pudo eliminar", title, HEIGHT);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtHoraPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraPruebaActionPerformed
        
    }//GEN-LAST:event_txtHoraPruebaActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        SimpleDateFormat inputFormat = new SimpleDateFormat("yyyy/MM/dd");
        try{
            Date fecha = inputFormat.parse(this.txtFechaPrueba.getText());
            Pruebas p = new Pruebas(Integer.parseInt(this.txtIDPRUEBA.getText()), this.txtCedulaOficial.getText(), this.txtCedulaCliente.getText(), this.txtObservaciones.getText(), Integer.parseInt(this.txtNota.getText()), this.txtEstado.getText(), fecha, this.txtHoraPrueba.getText());
            this.control.actulizar(p);
            
        }catch(ParseException ex){
            JOptionPane.showMessageDialog(this, "Error no se pudo actualizar", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        SimpleDateFormat inputFormat = new SimpleDateFormat("yyyy/MM/dd");
        try{
            Date fecha = inputFormat.parse(this.txtFechaPrueba.getText());
            Pruebas p = new Pruebas(Integer.parseInt(this.txtIDPRUEBA.getText()), this.txtCedulaOficial.getText(), this.txtCedulaCliente.getText(), this.txtObservaciones.getText(), Integer.parseInt(this.txtNota.getText()), this.txtEstado.getText(), fecha, this.txtHoraPrueba.getText());
            this.control.insertar(p);
            this.limpiar();
        }catch(ParseException ex){
            JOptionPane.showMessageDialog(this, "Error no se pudo ingresa cita", title, HEIGHT);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    public void cargardatos(Pruebas p) {
        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        txtFechaPrueba.setText(formatoFecha.format(p.getFecha()));

        this.txtCedulaCliente.setText(p.getCedulaCliente());
        this.txtCedulaOficial.setText(p.getCedulaOficial());
//        this.txtFechaPrueba.setText(p.getFecha());
        this.txtHoraPrueba.setText(p.getHora());
        this.txtNota.setText(String.valueOf(p.getNota()));
        this.txtEstado.setText(p.getEstado());
    }

    public void notificar(String msj, int tipo) {
        JOptionPane.showMessageDialog(this, "notificacion", "Error", tipo);
    }

    public void mostrarTodo(ArrayList<PruebasDTO> lista) {
        if (lista.isEmpty()) {
        limpiar();
        return;
     }
        PruebasDTO p = lista.get(0);
        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd HH  "); 
        txtFechaPrueba.setText(formatoFecha.format(p.getFecha()));
        txtIDPRUEBA.setText(String.valueOf(p.getIdprueba()));
        txtCedulaCliente.setText(String.valueOf(p.getCedulaCliente()));
        txtCedulaOficial.setText(String.valueOf(p.getCedulaOficial()));
        txtEstado.setText(p.getEstado());
        txtHoraPrueba.setText(p.getHora());
        txtNota.setText(String.valueOf(p.getNota()));
        txtObservaciones.setText(p.getObservaciones());
    }
    public void mostrarTabla(Citas[] citas,Clientes[] clientes) {
        SimpleDateFormat Fecha = new SimpleDateFormat("yyyyMMdd");
        DefaultTableModel model=new DefaultTableModel();
        model.addColumn("Cédula");
        model.addColumn("NombreCompleto");
        model.addColumn("Fecha");
        model.addColumn("Hora");
        
        for(int x=0;x<citas.length;x++){
            try{
              String date=Fecha.format(citas[x].getFecha());
              model.addRow(new Object[]{citas[x].getCedula(),clientes[x].getNombre(),Fecha.parse(date),citas[x].getHora()});
            }catch(ParseException ex){
                JOptionPane.showMessageDialog(this, "Error en la fecha", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
        this.tabla.setModel(model);
    }
        public void limpiar() {
        this.txtNombreCliente.setText("");
        this.txtEstado.setText("");
        this.txtNota.setText("");
        this.txtObservaciones.setText("");
        this.txtNombreOficial.setText("");
        this.txtCedulaOficial.setText("");
        this.txtPresente.setSelected(true);
        this.txtObservaciones.setEnabled(true);
        this.txtNota.setEnabled(true);
    }
        private void Habilitar(){
         
         this.txtNota.setEnabled(true);
         this.txtObservaciones.setEnabled(true);
         this.txtCedulaOficial.setEnabled(true);
    }
    private void Desabilitar(){
         
         this.txtNota.setEnabled(false);
         this.txtObservaciones.setEnabled(false);
         this.txtCedulaOficial.setEnabled(false);
    }
         public void cambiarEstados() {
        this.btnAgregar.setEnabled(!this.btnAgregar.isEnabled());
        this.btnModificar.setEnabled(!this.btnModificar.isEnabled());
        this.btnEliminar.setEnabled(!this.btnEliminar.isEnabled());
    }
//    private void buscarNombres(){
//        
//    }     
         
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lbliDOFICIAL;
    private javax.swing.JTable tabla;
    private javax.swing.JRadioButton txtAusente;
    private javax.swing.JTextField txtCedulaCliente;
    private javax.swing.JTextField txtCedulaOficial;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFechaPrueba;
    private javax.swing.JTextField txtHoraPrueba;
    private javax.swing.JTextField txtIDPRUEBA;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreOficial;
    private javax.swing.JTextField txtNota;
    private javax.swing.JTextField txtObservaciones;
    private javax.swing.JRadioButton txtPresente;
    // End of variables declaration//GEN-END:variables
}
